### PR TITLE
Crossbuild sbt 1.0 and 0.13

### PR DESCRIPTION
**Pull request by el-dom**
Crossbuilds this plugin for 1.0 und 0.13 and uses latest versions of dependencies

### CODE REVIEW

**Comment by el-dom** [comment]
@magro 
Since you said you'd like this [here](https://github.com/Galeria-Kaufhof/pillar/pull/23#issuecomment-321891479), now's your chance.

**Comment by witi83** [comment]
@magro any news? Is there something I could help you with?

**Comment by magro** [comment]
Awesome! Thanks @el-dom for the PR and @witi83 for the ping! :-) Sorry for responding that late, got off my list. I'll release this tomorrow or this weekend.

**Comment by magro** [comment]
I just released it as 2.1.3

**Pull request merged**
