### PR TITLE
ignore dotfiles and setup scripted sbt test

### PR DESCRIPTION
**Pull request by davidnadeau**
This is to solve https://github.com/inoio/sbt-pillar-plugin/issues/16 
I've added the filter to ignore dot files. I have also added a test to ensure that this is working as expected, following this guide: http://www.scala-sbt.org/release/docs/Testing-sbt-plugins.html

One imported thing about the test. Make sure to change the build.sbt project version to -SNAPSHOT before running `sbt scripted`, as `sbt scripted` will publish the plugin locally. Also you need a cassandra db running locally.

### CODE REVIEW

**Comment by magro** [comment]
Awesome! It's it possible to let scripted tests run on travis? IIRC it's possible to declare a dependency on a running cassandra.

**Comment by davidnadeau** [comment]
Good idea, done.

**Comment by magro** [comment]
Even more awesome! I'm release when I'm back from vacation.

**Comment by magro** [comment]
I just released this with 2.1.2

**Pull request merged**
